# definis l'image de base du front
FROM node:22-alpine 

# definis le repertoire de travail dans le container 
WORKDIR /app 

# copie du package.json et package-locnk.json dans le repertoire de travail (/app)
COPY package*.json . /

# installation des dependances 
RUN npm install 

# exosition du port 
EXPOSE 5173 

# commande executee quand le container tourne
CMD ["npm", "run", "dev"]

