services:
  # on definis le container du front end React
  frontend:
    # definis le nom du container
    container_name: frontend
    # definis le path pour acceder au DockerFile du container
    build: ./frontend
    # permet de definir les volumes
    volumes:
      # on lie le dossier frontend local avec le dosser du container
      # le premier correspond au dossier local
      # le second au dossier dans le container
      - ./frontend:/app
      # on lie le node_module du container a rien pour eviter les problemes de compatibilite
      - /app/node_modules
    # on mapp le port de la machine local avec celui du container
    # le premier est le port sur la machine local
    # le second correspond au port du container
    ports:
      - "5173:5173"

  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    container_name: database
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
